// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: bookings.sql

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const listBookings = `-- name: ListBookings :many
SELECT id, user_id, title, location, image, check_in, check_out, guests, status, price, amenities, created_at FROM bookings
WHERE user_id = $1
  AND ($2::text IS NULL OR status = $2::text)
ORDER BY check_in DESC
`

type ListBookingsParams struct {
	UserID uuid.UUID   `json:"user_id"`
	Status pgtype.Text `json:"status"`
}

func (q *Queries) ListBookings(ctx context.Context, arg ListBookingsParams) ([]Booking, error) {
	rows, err := q.db.Query(ctx, listBookings, arg.UserID, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Booking{}
	for rows.Next() {
		var i Booking
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Location,
			&i.Image,
			&i.CheckIn,
			&i.CheckOut,
			&i.Guests,
			&i.Status,
			&i.Price,
			&i.Amenities,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
