// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: membership.sql

package repository

import (
	"context"

	"github.com/google/uuid"
)

const listMembershipBenefits = `-- name: ListMembershipBenefits :many
SELECT id, name, golden, platinum, diamond, sort_order FROM membership_benefits ORDER BY sort_order ASC, id ASC
`

func (q *Queries) ListMembershipBenefits(ctx context.Context) ([]MembershipBenefit, error) {
	rows, err := q.db.Query(ctx, listMembershipBenefits)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MembershipBenefit{}
	for rows.Next() {
		var i MembershipBenefit
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Golden,
			&i.Platinum,
			&i.Diamond,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUserTier = `-- name: UpdateUserTier :one
UPDATE users
SET membership_tier = $2,
    updated_at = now()
WHERE id = $1
RETURNING id, first_name, last_name, email, phone, password_hash, avatar, membership_tier, membership_id, member_since, expiry_date, points, lifetime_points, created_at, updated_at
`

type UpdateUserTierParams struct {
	ID             uuid.UUID      `json:"id"`
	MembershipTier MembershipTier `json:"membership_tier"`
}

func (q *Queries) UpdateUserTier(ctx context.Context, arg UpdateUserTierParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserTier, arg.ID, arg.MembershipTier)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Phone,
		&i.PasswordHash,
		&i.Avatar,
		&i.MembershipTier,
		&i.MembershipID,
		&i.MemberSince,
		&i.ExpiryDate,
		&i.Points,
		&i.LifetimePoints,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
