// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repository

import (
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
)

type MembershipTier string

const (
	MembershipTierBasic    MembershipTier = "Basic"
	MembershipTierGolden   MembershipTier = "Golden"
	MembershipTierPlatinum MembershipTier = "Platinum"
	MembershipTierDiamond  MembershipTier = "Diamond"
)

func (e *MembershipTier) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MembershipTier(s)
	case string:
		*e = MembershipTier(s)
	default:
		return fmt.Errorf("unsupported scan type for MembershipTier: %T", src)
	}
	return nil
}

type NullMembershipTier struct {
	MembershipTier MembershipTier `json:"membership_tier"`
	Valid          bool           `json:"valid"` // Valid is true if MembershipTier is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMembershipTier) Scan(value interface{}) error {
	if value == nil {
		ns.MembershipTier, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MembershipTier.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMembershipTier) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MembershipTier), nil
}

type User struct {
	ID             uuid.UUID      `json:"id"`
	FirstName      string         `json:"first_name"`
	LastName       string         `json:"last_name"`
	Email          string         `json:"email"`
	Phone          string         `json:"phone"`
	PasswordHash   string         `json:"password_hash"`
	Avatar         string         `json:"avatar"`
	MembershipTier MembershipTier `json:"membership_tier"`
	MembershipID   string         `json:"membership_id"`
	MemberSince    time.Time      `json:"member_since"`
	ExpiryDate     time.Time      `json:"expiry_date"`
	Points         int64          `json:"points"`
	LifetimePoints int64          `json:"lifetime_points"`
	CreatedAt      time.Time      `json:"created_at"`
	UpdatedAt      time.Time      `json:"updated_at"`
}
