// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repository

import (
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
)

type MembershipTier string

const (
	MembershipTierBasic    MembershipTier = "Basic"
	MembershipTierGolden   MembershipTier = "Golden"
	MembershipTierPlatinum MembershipTier = "Platinum"
	MembershipTierDiamond  MembershipTier = "Diamond"
)

func (e *MembershipTier) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MembershipTier(s)
	case string:
		*e = MembershipTier(s)
	default:
		return fmt.Errorf("unsupported scan type for MembershipTier: %T", src)
	}
	return nil
}

type NullMembershipTier struct {
	MembershipTier MembershipTier `json:"membership_tier"`
	Valid          bool           `json:"valid"` // Valid is true if MembershipTier is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMembershipTier) Scan(value interface{}) error {
	if value == nil {
		ns.MembershipTier, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MembershipTier.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMembershipTier) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MembershipTier), nil
}

type MembershipBenefit struct {
	ID        int64  `json:"id"`
	Name      string `json:"name"`
	Golden    string `json:"golden"`
	Platinum  string `json:"platinum"`
	Diamond   string `json:"diamond"`
	SortOrder int32  `json:"sort_order"`
}

type PointsTransaction struct {
	ID           int64     `json:"id"`
	UserID       uuid.UUID `json:"user_id"`
	OccurredAt   time.Time `json:"occurred_at"`
	Description  string    `json:"description"`
	Category     string    `json:"category"`
	TxnType      string    `json:"txn_type"`
	Points       int64     `json:"points"`
	Amount       string    `json:"amount"`
	BalanceAfter int64     `json:"balance_after"`
}

type Redemption struct {
	ID          uuid.UUID `json:"id"`
	UserID      uuid.UUID `json:"user_id"`
	RewardID    uuid.UUID `json:"reward_id"`
	PointsSpent int64     `json:"points_spent"`
	CreatedAt   time.Time `json:"created_at"`
}

type Reward struct {
	ID             uuid.UUID `json:"id"`
	Image          string    `json:"image"`
	Title          string    `json:"title"`
	Description    string    `json:"description"`
	PointsRequired int64     `json:"points_required"`
	Category       string    `json:"category"`
	CreatedAt      time.Time `json:"created_at"`
}

type User struct {
	ID             uuid.UUID      `json:"id"`
	FirstName      string         `json:"first_name"`
	LastName       string         `json:"last_name"`
	Email          string         `json:"email"`
	Phone          string         `json:"phone"`
	PasswordHash   string         `json:"password_hash"`
	Avatar         string         `json:"avatar"`
	MembershipTier MembershipTier `json:"membership_tier"`
	MembershipID   string         `json:"membership_id"`
	MemberSince    time.Time      `json:"member_since"`
	ExpiryDate     time.Time      `json:"expiry_date"`
	Points         int64          `json:"points"`
	LifetimePoints int64          `json:"lifetime_points"`
	CreatedAt      time.Time      `json:"created_at"`
	UpdatedAt      time.Time      `json:"updated_at"`
}
