// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: offers.sql

package repository

import (
	"context"
)

const listOffers = `-- name: ListOffers :many
SELECT id, image, title, description, expiry, discount, created_at FROM offers ORDER BY expiry ASC
`

func (q *Queries) ListOffers(ctx context.Context) ([]Offer, error) {
	rows, err := q.db.Query(ctx, listOffers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Offer{}
	for rows.Next() {
		var i Offer
		if err := rows.Scan(
			&i.ID,
			&i.Image,
			&i.Title,
			&i.Description,
			&i.Expiry,
			&i.Discount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
