// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: payment_methods.sql

package repository

import (
	"context"

	"github.com/google/uuid"
)

const clearDefaultPaymentMethods = `-- name: ClearDefaultPaymentMethods :exec
UPDATE payment_methods SET is_default = false WHERE user_id = $1
`

func (q *Queries) ClearDefaultPaymentMethods(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, clearDefaultPaymentMethods, userID)
	return err
}

const insertPaymentMethod = `-- name: InsertPaymentMethod :one
INSERT INTO payment_methods (user_id, brand, last_four, exp_month, exp_year, name, is_default)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, user_id, brand, last_four, exp_month, exp_year, name, is_default, created_at
`

type InsertPaymentMethodParams struct {
	UserID    uuid.UUID `json:"user_id"`
	Brand     string    `json:"brand"`
	LastFour  string    `json:"last_four"`
	ExpMonth  string    `json:"exp_month"`
	ExpYear   string    `json:"exp_year"`
	Name      string    `json:"name"`
	IsDefault bool      `json:"is_default"`
}

func (q *Queries) InsertPaymentMethod(ctx context.Context, arg InsertPaymentMethodParams) (PaymentMethod, error) {
	row := q.db.QueryRow(ctx, insertPaymentMethod,
		arg.UserID,
		arg.Brand,
		arg.LastFour,
		arg.ExpMonth,
		arg.ExpYear,
		arg.Name,
		arg.IsDefault,
	)
	var i PaymentMethod
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Brand,
		&i.LastFour,
		&i.ExpMonth,
		&i.ExpYear,
		&i.Name,
		&i.IsDefault,
		&i.CreatedAt,
	)
	return i, err
}

const listPaymentMethods = `-- name: ListPaymentMethods :many
SELECT id, user_id, brand, last_four, exp_month, exp_year, name, is_default, created_at FROM payment_methods
WHERE user_id = $1
ORDER BY is_default DESC, created_at DESC
`

func (q *Queries) ListPaymentMethods(ctx context.Context, userID uuid.UUID) ([]PaymentMethod, error) {
	rows, err := q.db.Query(ctx, listPaymentMethods, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PaymentMethod{}
	for rows.Next() {
		var i PaymentMethod
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Brand,
			&i.LastFour,
			&i.ExpMonth,
			&i.ExpYear,
			&i.Name,
			&i.IsDefault,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
