// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: payments.sql

package repository

import (
	"context"

	"github.com/google/uuid"
)

const getPaymentByTxRef = `-- name: GetPaymentByTxRef :one
SELECT id, user_id, tx_ref, description, amount, currency, status, payment_method, checkout_url, occurred_at, purpose, target_tier FROM payments WHERE tx_ref = $1
`

func (q *Queries) GetPaymentByTxRef(ctx context.Context, txRef string) (Payment, error) {
	row := q.db.QueryRow(ctx, getPaymentByTxRef, txRef)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TxRef,
		&i.Description,
		&i.Amount,
		&i.Currency,
		&i.Status,
		&i.PaymentMethod,
		&i.CheckoutUrl,
		&i.OccurredAt,
		&i.Purpose,
		&i.TargetTier,
	)
	return i, err
}

const insertPayment = `-- name: InsertPayment :one
INSERT INTO payments (user_id, tx_ref, description, amount, currency, status, payment_method, checkout_url, purpose, target_tier)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, user_id, tx_ref, description, amount, currency, status, payment_method, checkout_url, occurred_at, purpose, target_tier
`

type InsertPaymentParams struct {
	UserID        uuid.UUID `json:"user_id"`
	TxRef         string    `json:"tx_ref"`
	Description   string    `json:"description"`
	Amount        string    `json:"amount"`
	Currency      string    `json:"currency"`
	Status        string    `json:"status"`
	PaymentMethod string    `json:"payment_method"`
	CheckoutUrl   string    `json:"checkout_url"`
	Purpose       string    `json:"purpose"`
	TargetTier    string    `json:"target_tier"`
}

func (q *Queries) InsertPayment(ctx context.Context, arg InsertPaymentParams) (Payment, error) {
	row := q.db.QueryRow(ctx, insertPayment,
		arg.UserID,
		arg.TxRef,
		arg.Description,
		arg.Amount,
		arg.Currency,
		arg.Status,
		arg.PaymentMethod,
		arg.CheckoutUrl,
		arg.Purpose,
		arg.TargetTier,
	)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TxRef,
		&i.Description,
		&i.Amount,
		&i.Currency,
		&i.Status,
		&i.PaymentMethod,
		&i.CheckoutUrl,
		&i.OccurredAt,
		&i.Purpose,
		&i.TargetTier,
	)
	return i, err
}

const listPayments = `-- name: ListPayments :many
SELECT id, user_id, tx_ref, description, amount, currency, status, payment_method, checkout_url, occurred_at, purpose, target_tier FROM payments
WHERE user_id = $1
ORDER BY occurred_at DESC
`

func (q *Queries) ListPayments(ctx context.Context, userID uuid.UUID) ([]Payment, error) {
	rows, err := q.db.Query(ctx, listPayments, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Payment{}
	for rows.Next() {
		var i Payment
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TxRef,
			&i.Description,
			&i.Amount,
			&i.Currency,
			&i.Status,
			&i.PaymentMethod,
			&i.CheckoutUrl,
			&i.OccurredAt,
			&i.Purpose,
			&i.TargetTier,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePaymentStatus = `-- name: UpdatePaymentStatus :one
UPDATE payments
SET status = $2
WHERE tx_ref = $1
RETURNING id, user_id, tx_ref, description, amount, currency, status, payment_method, checkout_url, occurred_at, purpose, target_tier
`

type UpdatePaymentStatusParams struct {
	TxRef  string `json:"tx_ref"`
	Status string `json:"status"`
}

func (q *Queries) UpdatePaymentStatus(ctx context.Context, arg UpdatePaymentStatusParams) (Payment, error) {
	row := q.db.QueryRow(ctx, updatePaymentStatus, arg.TxRef, arg.Status)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TxRef,
		&i.Description,
		&i.Amount,
		&i.Currency,
		&i.Status,
		&i.PaymentMethod,
		&i.CheckoutUrl,
		&i.OccurredAt,
		&i.Purpose,
		&i.TargetTier,
	)
	return i, err
}
