// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: points.sql

package repository

import (
	"context"

	"github.com/google/uuid"
)

const addUserPoints = `-- name: AddUserPoints :one
UPDATE users
SET points = points + $2,
    lifetime_points = lifetime_points + $2,
    updated_at = now()
WHERE id = $1
RETURNING points
`

type AddUserPointsParams struct {
	ID     uuid.UUID `json:"id"`
	Points int64     `json:"points"`
}

func (q *Queries) AddUserPoints(ctx context.Context, arg AddUserPointsParams) (int64, error) {
	row := q.db.QueryRow(ctx, addUserPoints, arg.ID, arg.Points)
	var points int64
	err := row.Scan(&points)
	return points, err
}

const deductUserPoints = `-- name: DeductUserPoints :one
UPDATE users
SET points = points - $2,
    updated_at = now()
WHERE id = $1 AND points >= $2
RETURNING points
`

type DeductUserPointsParams struct {
	ID     uuid.UUID `json:"id"`
	Points int64     `json:"points"`
}

// Returns no row when the balance is insufficient, letting the caller reject
// the redemption atomically.
func (q *Queries) DeductUserPoints(ctx context.Context, arg DeductUserPointsParams) (int64, error) {
	row := q.db.QueryRow(ctx, deductUserPoints, arg.ID, arg.Points)
	var points int64
	err := row.Scan(&points)
	return points, err
}

const insertPointsTransaction = `-- name: InsertPointsTransaction :one
INSERT INTO points_transactions (user_id, description, category, txn_type, points, amount, balance_after)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, user_id, occurred_at, description, category, txn_type, points, amount, balance_after
`

type InsertPointsTransactionParams struct {
	UserID       uuid.UUID `json:"user_id"`
	Description  string    `json:"description"`
	Category     string    `json:"category"`
	TxnType      string    `json:"txn_type"`
	Points       int64     `json:"points"`
	Amount       string    `json:"amount"`
	BalanceAfter int64     `json:"balance_after"`
}

func (q *Queries) InsertPointsTransaction(ctx context.Context, arg InsertPointsTransactionParams) (PointsTransaction, error) {
	row := q.db.QueryRow(ctx, insertPointsTransaction,
		arg.UserID,
		arg.Description,
		arg.Category,
		arg.TxnType,
		arg.Points,
		arg.Amount,
		arg.BalanceAfter,
	)
	var i PointsTransaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.OccurredAt,
		&i.Description,
		&i.Category,
		&i.TxnType,
		&i.Points,
		&i.Amount,
		&i.BalanceAfter,
	)
	return i, err
}

const listPointsHistory = `-- name: ListPointsHistory :many
SELECT id, user_id, occurred_at, description, category, txn_type, points, amount, balance_after FROM points_transactions
WHERE user_id = $1
ORDER BY occurred_at DESC, id DESC
`

func (q *Queries) ListPointsHistory(ctx context.Context, userID uuid.UUID) ([]PointsTransaction, error) {
	rows, err := q.db.Query(ctx, listPointsHistory, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PointsTransaction{}
	for rows.Next() {
		var i PointsTransaction
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.OccurredAt,
			&i.Description,
			&i.Category,
			&i.TxnType,
			&i.Points,
			&i.Amount,
			&i.BalanceAfter,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
