// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: rewards.sql

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getReward = `-- name: GetReward :one
SELECT id, image, title, description, points_required, category, created_at FROM rewards WHERE id = $1
`

func (q *Queries) GetReward(ctx context.Context, id uuid.UUID) (Reward, error) {
	row := q.db.QueryRow(ctx, getReward, id)
	var i Reward
	err := row.Scan(
		&i.ID,
		&i.Image,
		&i.Title,
		&i.Description,
		&i.PointsRequired,
		&i.Category,
		&i.CreatedAt,
	)
	return i, err
}

const insertRedemption = `-- name: InsertRedemption :one
INSERT INTO redemptions (user_id, reward_id, points_spent)
VALUES ($1, $2, $3)
RETURNING id, user_id, reward_id, points_spent, created_at
`

type InsertRedemptionParams struct {
	UserID      uuid.UUID `json:"user_id"`
	RewardID    uuid.UUID `json:"reward_id"`
	PointsSpent int64     `json:"points_spent"`
}

func (q *Queries) InsertRedemption(ctx context.Context, arg InsertRedemptionParams) (Redemption, error) {
	row := q.db.QueryRow(ctx, insertRedemption, arg.UserID, arg.RewardID, arg.PointsSpent)
	var i Redemption
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RewardID,
		&i.PointsSpent,
		&i.CreatedAt,
	)
	return i, err
}

const listRewards = `-- name: ListRewards :many
SELECT id, image, title, description, points_required, category, created_at FROM rewards
WHERE $1::text IS NULL OR category = $1::text
ORDER BY points_required ASC
`

func (q *Queries) ListRewards(ctx context.Context, category pgtype.Text) ([]Reward, error) {
	rows, err := q.db.Query(ctx, listRewards, category)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Reward{}
	for rows.Next() {
		var i Reward
		if err := rows.Scan(
			&i.ID,
			&i.Image,
			&i.Title,
			&i.Description,
			&i.PointsRequired,
			&i.Category,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
