// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: surveys.sql

package repository

import (
	"context"

	"github.com/google/uuid"
)

const getSurvey = `-- name: GetSurvey :one
SELECT user_id, visit_purpose, preferred_accommodation, interests, travel_frequency, special_occasions, additional_notes, created_at, updated_at FROM surveys WHERE user_id = $1
`

func (q *Queries) GetSurvey(ctx context.Context, userID uuid.UUID) (Survey, error) {
	row := q.db.QueryRow(ctx, getSurvey, userID)
	var i Survey
	err := row.Scan(
		&i.UserID,
		&i.VisitPurpose,
		&i.PreferredAccommodation,
		&i.Interests,
		&i.TravelFrequency,
		&i.SpecialOccasions,
		&i.AdditionalNotes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertSurvey = `-- name: UpsertSurvey :one
INSERT INTO surveys (
    user_id, visit_purpose, preferred_accommodation, interests,
    travel_frequency, special_occasions, additional_notes
) VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (user_id) DO UPDATE SET
    visit_purpose           = EXCLUDED.visit_purpose,
    preferred_accommodation = EXCLUDED.preferred_accommodation,
    interests               = EXCLUDED.interests,
    travel_frequency        = EXCLUDED.travel_frequency,
    special_occasions       = EXCLUDED.special_occasions,
    additional_notes        = EXCLUDED.additional_notes,
    updated_at              = now()
RETURNING user_id, visit_purpose, preferred_accommodation, interests, travel_frequency, special_occasions, additional_notes, created_at, updated_at
`

type UpsertSurveyParams struct {
	UserID                 uuid.UUID `json:"user_id"`
	VisitPurpose           string    `json:"visit_purpose"`
	PreferredAccommodation []string  `json:"preferred_accommodation"`
	Interests              []string  `json:"interests"`
	TravelFrequency        string    `json:"travel_frequency"`
	SpecialOccasions       string    `json:"special_occasions"`
	AdditionalNotes        string    `json:"additional_notes"`
}

func (q *Queries) UpsertSurvey(ctx context.Context, arg UpsertSurveyParams) (Survey, error) {
	row := q.db.QueryRow(ctx, upsertSurvey,
		arg.UserID,
		arg.VisitPurpose,
		arg.PreferredAccommodation,
		arg.Interests,
		arg.TravelFrequency,
		arg.SpecialOccasions,
		arg.AdditionalNotes,
	)
	var i Survey
	err := row.Scan(
		&i.UserID,
		&i.VisitPurpose,
		&i.PreferredAccommodation,
		&i.Interests,
		&i.TravelFrequency,
		&i.SpecialOccasions,
		&i.AdditionalNotes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
