// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (first_name, last_name, email, phone, password_hash, membership_id)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, first_name, last_name, email, phone, password_hash, avatar, membership_tier, membership_id, member_since, expiry_date, points, lifetime_points, created_at, updated_at
`

type CreateUserParams struct {
	FirstName    string `json:"first_name"`
	LastName     string `json:"last_name"`
	Email        string `json:"email"`
	Phone        string `json:"phone"`
	PasswordHash string `json:"password_hash"`
	MembershipID string `json:"membership_id"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.FirstName,
		arg.LastName,
		arg.Email,
		arg.Phone,
		arg.PasswordHash,
		arg.MembershipID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Phone,
		&i.PasswordHash,
		&i.Avatar,
		&i.MembershipTier,
		&i.MembershipID,
		&i.MemberSince,
		&i.ExpiryDate,
		&i.Points,
		&i.LifetimePoints,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, first_name, last_name, email, phone, password_hash, avatar, membership_tier, membership_id, member_since, expiry_date, points, lifetime_points, created_at, updated_at FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Phone,
		&i.PasswordHash,
		&i.Avatar,
		&i.MembershipTier,
		&i.MembershipID,
		&i.MemberSince,
		&i.ExpiryDate,
		&i.Points,
		&i.LifetimePoints,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, first_name, last_name, email, phone, password_hash, avatar, membership_tier, membership_id, member_since, expiry_date, points, lifetime_points, created_at, updated_at FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Phone,
		&i.PasswordHash,
		&i.Avatar,
		&i.MembershipTier,
		&i.MembershipID,
		&i.MemberSince,
		&i.ExpiryDate,
		&i.Points,
		&i.LifetimePoints,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET first_name = COALESCE($1, first_name),
    last_name  = COALESCE($2, last_name),
    phone      = COALESCE($3, phone),
    avatar     = COALESCE($4, avatar),
    updated_at = now()
WHERE id = $5
RETURNING id, first_name, last_name, email, phone, password_hash, avatar, membership_tier, membership_id, member_since, expiry_date, points, lifetime_points, created_at, updated_at
`

type UpdateUserParams struct {
	FirstName pgtype.Text `json:"first_name"`
	LastName  pgtype.Text `json:"last_name"`
	Phone     pgtype.Text `json:"phone"`
	Avatar    pgtype.Text `json:"avatar"`
	ID        uuid.UUID   `json:"id"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.FirstName,
		arg.LastName,
		arg.Phone,
		arg.Avatar,
		arg.ID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Phone,
		&i.PasswordHash,
		&i.Avatar,
		&i.MembershipTier,
		&i.MembershipID,
		&i.MemberSince,
		&i.ExpiryDate,
		&i.Points,
		&i.LifetimePoints,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
